### PR TITLE
New ElkanKMeansTest to show Nondeterminism

### PR DESCRIPTION
**Pull request by TKlerx**
new Test that shows that ElkanKMeansTest is not deterministic because for the same input it yields different results in some runs.

If you run the new ElkanKMeansTestNew a couple of times, you will not get the same results for the found output, even though the seed and the dataSet are always the same (read from file).
Sometimes the test fails and sometimes it does not.

(I hope this is reproducible now, at least on my machine where the tests always passed before (Oracle JDK 1.8.40)).

### CODE REVIEW

**Comment by EdwardRaff** [comment]
I can still not reproduce this bug on any of my machines. Ran 30 times with JDK 8u40, 8u45 and 7u75

**Comment by TKlerx** [comment]
Maybe, I found a correlation: The more CPU Cores the system has, the less likely it is to reproduce the behavior. I found that with 8 logical cores I cannot reproduce it.
With 4 cores the test fails sometimes and with 2 cores it fails almost always.

As I wrote in the mail I will try to figure out why when I have some time. This is a really tricky one...

**Comment by EdwardRaff** [comment]
does it fail at all with just 1 core ?

**Comment by TKlerx** [comment]
I can only test this in a VM.
On the same VM it did not fail with 1 core and a lot of executions, but it does fail on the same VM with 2 cores.

**Pull request closed without merging**
