### PR TITLE
(mainly) Java/Javadoc warnings removed

### PR DESCRIPTION
**Pull request by TKlerx**
* fixed javadoc errors/warnings, compile warnings
 *html in javadoc
 * unused java imports
 * missing serialVersionUID
* added SingleValueDistribution to DistributionSearch
* Changed every "new ArrayList<Double/Integer>" to new DoubleList/IntList

Sorry for this big pull request. Had to change something in almost every class.

### CODE REVIEW

**Comment by EdwardRaff** [comment]
What is the point in having the SingleValueDistribution? It doesn't look like you finished implementing it. 

Can you remove the empty comments for the serialVersionUID? No point in putting in empty comment blocks.

**Comment by TKlerx** [comment]
> What is the point in having the SingleValueDistribution?

I am using the DistributionSearch to search for the best Distribution and if all the values are the same then this is the best distribution.

>It doesn't look like you finished implementing it.  

Sorry for that, is done.

>Can you remove the empty comments for the serialVersionUID? No point in putting in empty comment blocks.

eclipse auto generated them. Again sorry, all gone now.

**Comment by EdwardRaff** [comment]
Mostly looks good now. Would prefer not to include the SignleValue class though. The functionality should be obtainable from the Uniform dist with a range +- epsilon. However, the SingleValue class can never be a valid probability density function, so two of its methods can never be implemented correctly. This is because the integral from -inf to inf of the pdf where only a single point has a non-zero value can't be = 1. 

There is some code you commented out in DCD.java that I would prefer you put back, as it dosn't hurt and makes the code match the algorithm description (easier to go back and compare in the event of a bug). 

Not major, but whatever you used to modify comments also modified non-javadoc comments, which should really be left alone (& -> &amp; is not helpful in that case). More major is it expanded some occurrences of "&" in Strings for the GUI. It also modifed code in the auto-generated blocks, please remove those. 

You've also made some changes to DBSCAN that I don't understand the purpose of. 

What is the purpose of the change to LUPDecomposition linke 84? 

Please remove the changes to SingularValueDecomposition, unless they are reflecting changes made the the JAMA SVD implementation since the time I modified it. 

In the future it would probably be easier to stick to one thing per pull request.

**Comment by TKlerx** [comment]
>Would prefer not to include the SignleValue class though. The functionality should be obtainable from the Uniform dist with a range +- epsilon. However, the SingleValue class can never be a valid probability density function, so two of its methods can never be implemented correctly. This is because the integral from -inf to inf of the pdf where only a single point has a non-zero value can't be = 1. 

Done.

>There is some code you commented out in DCD.java that I would prefer you put back, as it dosn't hurt and makes the code match the algorithm description (easier to go back and compare in the event of a bug). 

Done.

>Not major, but whatever you used to modify comments also modified non-javadoc comments, which should really be left alone (& -> & is not helpful in that case). More major is it expanded some occurrences of "&" in Strings for the GUI. It also modifed code in the auto-generated blocks, please remove those. 

Used a RegExpr, but it replaced a bit too much. Sorry! Also done.

>You've also made some changes to DBSCAN that I don't understand the purpose of. 

Maybe, I use DBSCAN in the wrong way, but I have the following usecase:
I cluster some datapoints with DBSCAN and obtain an assignment.
Then I get some new datapoints and want to know whether they belong to some cluster or whether they are noise points. That's why I need the last vector collection and also need the NOISE constant to be public.

>What is the purpose of the change to LUPDecomposition linke 84? 

It removes a findbugs warning: 
```Check for oddness that won't work for negative numbers in jsat.linear.LUPDecomposition.det()
The code uses x % 2 == 1 to check to see if a value is odd, but this won't work for negative numbers (e.g., (-5) % 2 == -1). If this code is intending to check for oddness, consider using x & 1 == 1, or x % 2 != 0."```

I think I also replaced this in some other classes, but I can revert if you want.

>Please remove the changes to SingularValueDecomposition, unless they are reflecting changes made the the JAMA SVD implementation since the time I modified it. 

Done.

>In the future it would probably be easier to stick to one thing per pull request. 

Yeah, definitely. Big sorry, I am not used to the git workflow, yet.

**Comment by EdwardRaff** [comment]
>I think I also replaced this in some other classes, but I can revert if you want.

You can leave it, it was just weird. FindBugs doesn't matter in those cases since the input is always non-negative. 

>Maybe, I use DBSCAN in the wrong way, but I have the following usecase:
I cluster some datapoints with DBSCAN and obtain an assignment.
Then I get some new datapoints and want to know whether they belong to some cluster or whether they are noise points. That's why I need the last vector collection and also need the NOISE constant to be public.

Hmm. Please remove it for now, but we can think of how to integrate this in the future. My first thought is there should just be a class which takes the assignment array and builds a new VectorCollection to do assignments. But some algorithms like LSDBC take into account density, so just strait up assignment to the nearest neighbor might not make sense. But it wouldn't make sense for only DBSCAN to have that modification. We can talk about it more in another Issue/Enhancement request thread.

**Comment by TKlerx** [comment]
Done in 407badd26aef82d018a3e52445cb82ea7f613a3d
So I hope everything is fine now.

**Comment by EdwardRaff** [comment]
Yup. Thanks for doing all of that!

**Pull request merged**
