### PR TITLE
Serializable DataSets

### PR DESCRIPTION
**Pull request by Thorbur**
Made ClassificationDataSet and DataSet implement Serializable

### CODE REVIEW

**Comment by EdwardRaff** [comment]
Can you rebase so the merge doesn't look weird? 

Out of curiosity, what is your use case for serializing a dataset? Would me implementing a simple binary better fit a general use case?

**Comment by Thorbur** [comment]
I rebased it and hope it is okay now?
My use case, why I needed the serialization, is that I generate a larger data set of feature vectors over images, which are quite time consuming to compute. Thus, after I added all feature vectors with their corresponding labels to ClassificationDataSet, I want to store it before training my classifier. I also serialize the trained classifier, of course. But this way it's easy and quick to replace the classifier or recover from errors without the need to regenerate my dataset again.
I admit, maybe it would be better to store my data set in another universal format, but serialization turned out to be the quickest way. Or do you have any suggestion how to export it in another format? thx

**Comment by davidmoten** [comment]
Kryo might be useful for you. I believe it can serialize objects without requiring that they implement Serializable. There are other requirements to do with constructors but might be worth a look.

**Comment by chhh** [comment]
I had great success with FST serialization library. It's very fast, under
constant development here on github, and it canserialize stuff that does
not implement Serializeable.

**Comment by EdwardRaff** [comment]
@chhh and @davidmoten  both suggested other serialization options that will probably be faster than the default Java serialization. 

If you're just going to store the data, you really should be using some format. Any change to the DataSet classes could break your data for no good reason. You could use the `ARFFLoader.writeArffFile` or `LIBSVMLoader.write` methods to export your file, though they do have some unnecessary overhead since both store data as plain text, but both are also widely supported. 

I think a better option long term would be for me to add a importer/exporter format that just write out binary data.

**Comment by Thorbur** [comment]
@chhh & @davidmoten thanks for the hints. It's good to know that these tools exist.
@EdwardRaff The default serialization was working for me. However, I agree, it's much better to to store the data in a format like ARFF. I just switched now to `ARFFLoader.writeArffFile`, I wasn't aware that `ARFFLoader` is also capable of writing data sets besides just loading them ;).
Thank you for the support. Indeed, it would be also nice to have some universal format for storing the trained models, but I guess that's not trivial.
Furthermore, I was testing `LIBSVMLoader.write` but encountered a bug. The write methods are missing a final `writer.flush`. I commited a fixed to my fork. Maybe you can merge it, but anyway it's just adding two simple lines.

**Comment by EdwardRaff** [comment]
@Thorbur good catch on the flush! I don't see that addition in these commits, so I just did it since it's simple. 

Yea, the name doesn't hint at support for writing! I don't think I want to merge this if there isn't a compelling use case, since I've made internal changes to DataSet before and I could see future changes that wouldn't be serialization compatible. 

Based on this conversation though I'm writing a "JSATLoader" (ideas for a better name?) that will be a simple binary format for reading and writing classification, regression, and "simple" datasets. I'm going to write it so that other languages could easily implement their own reader/writers. It won't take over the world or anything, but it should be more storage efficient and faster than all these human readable formats that people like to use for reasons I will never understand.

**Comment by Thorbur** [comment]
@EdwardRaff Okay, this way serialization is also not needed anymore on these classes. 
Your plans for "JSATLoader" sound great. I think you can keep that name, but maybe you can implement the writing capabilities in something like JSATExporter, like FileReader/FileWriter in the standard lib. Personally I also like it in rare cases to have a look at the data file to see if everything went fine. But I think it's really a matter of size. If the dataset is small it makes no difference to keep it readable or not. But if it gets bigger, people cannot spot it anyway and a binary format helps to save space. So I think binary makes more sense in a general perspective and if there is really a need to make it human readable one can implement a simple converter anyway.

**Comment by EdwardRaff** [comment]
I ended up calling it JSATData, with read and write in the same file to be consistent with that I already have. I made a small blog post [here](http://jsatml.blogspot.com/2015/11/a-binary-format-for-jsat-datasets.html) giving some example numbers on the time savigns and possible storage savings. It can save floats as 64 bit numbers, 32 bit numbers, shorts, and signed / unsigned bytes for integer datasets. Even when larger, its much faster. And when appropriate it can be much smaller. Since there is very little CPU processing needed to read/write the format, it should pair well with using things like GZip to further compressed the output. 

It may be faster to use NIO, but for now I think this is a big improvement and a better solution than serializing the dataset objects themselves :)

**Comment by Thorbur** [comment]
@EdwardRaff JSATData seems to be great :) Nice that you could implement it so quickly.

**Pull request closed without merging**
