### PR TITLE
equals and hashCode for (almost all) Distributions

### PR DESCRIPTION
**Pull request by TKlerx**
Added equals and hashCode methods for almost all distributions to be able to check whether two distributions are equal and to be able to use them in HashSets/Maps.

### CODE REVIEW

**Comment by EdwardRaff** [comment]
What is the use case for putting a distribution in a map as the key? 
Can you add test cases for the added code? (For distributions that don't have test cases yet, I don't expect you to add test cases covering the other methods).

**Comment by TKlerx** [comment]
I do not put the distribution as a key but use it as a value in a map `M`.
But when I do an equality check of `M` with another map `M'`, the equals method of the distribution is used.
I will add testcases asap.

**Comment by EdwardRaff** [comment]
I hadn't thought of that, makes sense.  I guess you set the distributions to a clean value (like, rounding to nearest 0.01), to avoid floating point issues in equality checks?

**Comment by chhh** [comment]
That would be very confusing if equals was not performed using exact
distribution parameters, especially considering the fact that sensitivity
to different parameters is different, so you'd need to devise and document
all the tolerances.

**Comment by EdwardRaff** [comment]
I meant that he in his code would round the distribution values to a value so that the exact match of floating point vAlues would work. Not that he should make the equals method do rounding.

**Comment by TKlerx** [comment]
Please have a look again. I hope this is what you expected.

**Comment by EdwardRaff** [comment]
Looks good to me. Thanks again!

**Pull request merged**
